### ISSUE TITLE
 A conflict with CustomSkinLoader mod

### ISSUE THREAD

**Issue by WhitePisces0311** [ReillyGregorio/Doodads#3]
When i install Doodads  and [CustomSkinLoader](https://github.com/xfl03/MCCustomSkinLoader) together on minecraft vanilla server, the second layered skin and cape disappear regardless of whether online-mode are opened.But it is normal in single-player mode.
Server version:1.18.2

**Comment by WhitePisces0311** [comment]
I forgot one thing. I use Fabric sorry x_x

**Comment by ArcanePigeon** [comment]
Could I get the full mod list and mod versions?

**Comment by WhitePisces0311** [comment]
I've done a huge stupid thing.It should use the core downloaded from the fabric official website, while I used the minecraft vanilla core.So the mods didn't load correctly.Very sorry for wasting your time X_X Please forgive me
