### ISSUE TITLE
Suggestion: config to increase portable nether infected area

### ISSUE THREAD

**Issue by ironsnake345** [ReillyGregorio/Doodads#4]
Portable nether is a neat block, but since it only affects one block above itself, its uses are kind of limited. Even a baby piglin is tall enough that their head pokes a bit out of the affected zone and they start zombifying. Being able to increase the total area affected by a portable nether block - even just the height - would really open up some possibilities for my builds.

**Comment by ArcanePigeon** [comment]
The portable nether was never made to prevent piglin transformations. each feature of the block is a result of manipulating blocks that are normally effected by the nether and not actually having the above block be considered actual nether which as far as I could tell was not possible. Expanding the area of effect for the portable nether is no planned
